-- ============================================================
-- Migration 01: Create Relational Tables + Indexes + RLS
-- Safe to run on a FRESH Supabase database.
-- Run in: Supabase Dashboard → SQL Editor
-- After this, run 02_migrate_kv_data.sql to copy existing data.
-- ============================================================

BEGIN;

-- =====================
-- 1. CREATE TABLES
-- =====================

-- Users table (user_id is UUID to match Supabase Auth)
CREATE TABLE IF NOT EXISTS users (
  user_id     UUID          PRIMARY KEY,
  name        VARCHAR(255)  NOT NULL,
  email       VARCHAR(255)  UNIQUE NOT NULL,
  password    VARCHAR(255)  DEFAULT '',
  phone       VARCHAR(50)   DEFAULT '',
  role        VARCHAR(20)   NOT NULL DEFAULT 'normal_user'
                            CHECK (role IN ('normal_user', 'admin')),
  approved_by UUID          REFERENCES users(user_id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  is_active   BOOLEAN       NOT NULL DEFAULT TRUE
);

-- Dental vehicles table
CREATE TABLE IF NOT EXISTS dental_vehicles (
  vehicle_id    SERIAL        PRIMARY KEY,
  vehicle_name  VARCHAR(255)  NOT NULL,
  location_name VARCHAR(255)  NOT NULL DEFAULT '',
  latitude      DOUBLE PRECISION,
  longitude     DOUBLE PRECISION,
  available     BOOLEAN       NOT NULL DEFAULT TRUE,
  image_url     TEXT          DEFAULT ''
);

-- Services table
CREATE TABLE IF NOT EXISTS services (
  service_id       SERIAL         PRIMARY KEY,
  service_name     VARCHAR(255)   NOT NULL,
  description      TEXT           DEFAULT '',
  duration_minutes INT            DEFAULT 30,
  price            NUMERIC(10, 2) DEFAULT 0
);

-- Appointments table
CREATE TABLE IF NOT EXISTS appointments (
  appointment_id   SERIAL      PRIMARY KEY,
  user_id          UUID        NOT NULL REFERENCES users(user_id)           ON DELETE CASCADE,
  vehicle_id       INT         NOT NULL REFERENCES dental_vehicles(vehicle_id) ON DELETE CASCADE,
  service_id       INT         NOT NULL REFERENCES services(service_id)     ON DELETE CASCADE,
  appointment_date DATE        NOT NULL,
  appointment_time TIME        NOT NULL,
  status           VARCHAR(20) NOT NULL DEFAULT 'Pending'
                               CHECK (status IN ('Pending', 'Approved', 'Completed', 'Cancelled')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Sessions table (for custom auth tokens generated by the Hono server)
CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT        PRIMARY KEY,
  user_id    UUID        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================
-- 2. INDEXES
-- =====================

CREATE INDEX IF NOT EXISTS idx_users_email            ON users(email);
CREATE INDEX IF NOT EXISTS idx_appointments_user_id   ON appointments(user_id);
CREATE INDEX IF NOT EXISTS idx_appointments_vehicle_id ON appointments(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_appointments_date       ON appointments(appointment_date);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id        ON sessions(user_id);

-- =====================
-- 3. ROW LEVEL SECURITY
-- =====================

-- Enable RLS on all tables
ALTER TABLE users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE dental_vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE services        ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments    ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions        ENABLE ROW LEVEL SECURITY;

-- Drop existing policies first so this script is idempotent.
-- The Hono/Edge Function server uses the service_role key which bypasses RLS,
-- so these policies grant full access to all roles (including anon reads for vehicles/services).
DROP POLICY IF EXISTS "Service role full access on users"           ON users;
DROP POLICY IF EXISTS "Service role full access on dental_vehicles" ON dental_vehicles;
DROP POLICY IF EXISTS "Service role full access on services"        ON services;
DROP POLICY IF EXISTS "Service role full access on appointments"    ON appointments;
DROP POLICY IF EXISTS "Service role full access on sessions"        ON sessions;

CREATE POLICY "Service role full access on users"           ON users           FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on dental_vehicles" ON dental_vehicles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on services"        ON services        FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on appointments"    ON appointments    FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access on sessions"        ON sessions        FOR ALL USING (true) WITH CHECK (true);

COMMIT;

-- ============================================================
-- Migration 01 complete.
-- Next step: run 02_migrate_kv_data.sql to copy KV store data.
-- ============================================================
